title: Chris Stead -- Web, The Universe, and Everything
author: Chris Stead
email: cmstead@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  The ramblings of a software engineer working with Javascript
  driven to the brink of madness and reporting back from the edge.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: cm_stead
    github:  cmstead
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

url: "http://chrisstead.net"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-sitemap

paginate: 5
paginate_path: "/blog/page:num/"
